# Generated by Django 4.1.2 on 2022-11-04 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Emplaoyee',
            new_name='Employee',
        ),
    ]
